export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'
export const NEXT_QUESTION = 'NEXT_QUESTION'

export const FETCH_QUESTIONS_STARTED = 'FETCH_QUESTIONS_STARTED'
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
