export const SET_PLAYER_NAME = 'SET_PLAYER_NAME'
export const SET_CURRENT_QUESTION_INDEX = 'SET_CURRENT_QUESTION_INDEX'
export const SET_SELECTED_ANSWER_INDEX = 'SET_SELECTED_ANSWER_INDEX'
export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE'
export const SET_IS_FINISHED = 'SET_IS_FINISHED'

export const FETCH_QUESTIONS_STARTED = 'FETCH_QUESTIONS_STARTED'
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
